# Generated by Django 5.0.4 on 2024-05-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaran', '0012_alter_contact_options_alter_costumer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='view',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
