# Generated by Django 5.0.4 on 2024-05-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_product_savat_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
