# Generated by Django 5.0.4 on 2024-05-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='view',
        ),
    ]
